# Generated by Django 5.2.1 on 2025-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learning_type',
            field=models.CharField(choices=[('videos', 'Videos'), ('images', 'Images'), ('text_and_images', 'Text and Images')], max_length=20),
        ),
    ]
