# Generated by Django 5.2.1 on 2025-06-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='choice',
            new_name='description',
        ),
    ]
