# Generated by Django 5.2.1 on 2025-05-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
