# Generated by Django 5.2.1 on 2025-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_learning_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_group',
            field=models.CharField(choices=[('<15', 'Less than 15'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('30+', '30+')], default='16-20', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
