# Generated by Django 5.2.1 on 2025-06-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_choice_questionoption_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='description',
            new_name='choice',
        ),
    ]
