# Generated by Django 5.2.1 on 2025-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoingcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='learningplan',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='coursereward',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='profile',
        ),
        migrations.AddField(
            model_name='ongoingcourse',
            name='course_name',
            field=models.CharField(default='Unnamed Course', max_length=255),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='courses',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
