# Generated by Django 5.2.1 on 2025-05-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_remove_ongoingcourse_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='learningplan',
            name='courses',
        ),
        migrations.AddField(
            model_name='learningplan',
            name='courses',
            field=models.ManyToManyField(to='learn.course'),
        ),
    ]
