# Generated by Django 5.2.1 on 2025-05-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_course_remove_learningplan_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
