# Generated by Django 5.2.1 on 2025-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_completedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='availability',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='learn.course'),
        ),
    ]
