# Generated by Django 5.2.1 on 2025-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=True),
        ),
    ]
