# Generated by Django 5.2.1 on 2025-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_question_correct_answer_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(max_length=255),
        ),
    ]
