# Generated by Django 5.2.1 on 2025-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_alter_courseprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
