# Generated by Django 5.2.1 on 2025-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_courseresource_duration_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.JSONField(default=dict),
        ),
    ]
