# Generated by Django 5.2.1 on 2025-06-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_alter_usercourse_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='courses',
        ),
    ]
