# Generated by Django 5.2.1 on 2025-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_remove_tutor_availability_remove_tutor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
