# Generated by Django 5.2.1 on 2025-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
