# Generated by Django 5.2.1 on 2025-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_tutor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
