# Generated by Django 5.2.1 on 2025-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_alter_usercourse_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
