# Generated by Django 5.2.1 on 2025-06-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0019_section_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='completed',
        ),
    ]
