# Generated by Django 5.2.1 on 2025-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0020_remove_section_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='completed',
            field=models.TextField(default=''),
        ),
    ]
