# Generated by Django 5.2.1 on 2025-06-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0021_alter_usercourse_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='course',
        ),
    ]
