# Generated by Django 5.2.1 on 2025-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0022_remove_courseresource_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereward',
            name='course',
        ),
        migrations.AddField(
            model_name='coursereward',
            name='picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursereward',
            name='xp_target',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
