# Generated by Django 5.2.1 on 2025-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0026_userquizquestionresponse_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='completed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
